/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as artists from "../artists.js";
import type * as dashboard from "../dashboard.js";
import type * as featuredArtist from "../featuredArtist.js";
import type * as playerTracks from "../playerTracks.js";
import type * as tracks from "../tracks.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  artists: typeof artists;
  dashboard: typeof dashboard;
  featuredArtist: typeof featuredArtist;
  playerTracks: typeof playerTracks;
  tracks: typeof tracks;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
